[Travis] Disable core 2.4.2 builds as Travis can't install it anymore
For some strange reason....

Build log:
```
$ PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run -e $ENV
Processing minimal_core_242_ESP8266_1M_OTA (platform: https://github.com/TD-er/platform-espressif8266.git#patch/v1.8.0_Puya; board: esp01_1m; framework: arduino)
--------------------------------------------------------------------------------
Platform Manager: Installing git+https://github.com/TD-er/platform-espressif8266.git#patch/v1.8.0_Puya
git version 2.27.0
Cloning into '/home/travis/.platformio/.cache/tmp/pkg-installing-aktun99x'...
Platform Manager: espressif8266 @ 1.8.0+sha.9ffc857 has been installed!
The platform 'https://github.com/TD-er/platform-espressif8266.git#patch/v1.8.0_Puya' has been successfully installed!
The rest of the packages will be installed later depending on your build environment.
Tool Manager: Installing toolchain-xtensa @ ~1.40802.0
Downloading...
Unpacking...
Tool Manager: toolchain-xtensa @ 1.40802.0 has been installed!
Tool Manager: Installing framework-arduinoespressif8266 @ 2.20402.4-puya
Tool Manager: Warning! More than one package has been found by framework-arduinoespressif8266 @ 2.20402.4-puya requirements:
 - platformio/framework-arduinoespressif8266 @ 3.20704.0
 - jason2866/framework-arduinoespressif8266 @ 2.7.4.1
Tool Manager: Please specify detailed REQUIREMENTS using package owner and version (showed above) to avoid name conflicts
Error: Could not find the package with 'framework-arduinoespressif8266 @ 2.20402.4-puya' requirements for your system 'linux_x86_64'
The command "PLATFORMIO_BUILD_FLAGS="-D CONTINUOUS_INTEGRATION" platformio run -e $ENV" exited with 1.
```

Maybe @jason2866 does have an idea?